// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Typeform/users/datastore (interfaces: Users)

package mockdb

import (
	v1 "github.com/Typeform/users/transport/v1"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Users interface
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *_MockUsersRecorder
}

// Recorder for MockUsers (not exported)
type _MockUsersRecorder struct {
	mock *MockUsers
}

func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &_MockUsersRecorder{mock}
	return mock
}

func (_m *MockUsers) EXPECT() *_MockUsersRecorder {
	return _m.recorder
}

func (_m *MockUsers) GetUser(_param0 int) (*v1.User, error) {
	ret := _m.ctrl.Call(_m, "GetUser", _param0)
	ret0, _ := ret[0].(*v1.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockUsersRecorder) GetUser(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetUser", arg0)
}
